port: 
api_key: 
notification_sender: smpt
smtp:
  host: smtp.gmail.com
  port: 587
  username: 
  password: 
redis:
  host: 
  port: 6379
  password: 
  db: 1
forecast_service:
  base_url: 
  api_key: 