port: 8080
api_key: 
notification_sender: smtp
smtp:
  host: 
  port: 587
  username: 
  password: 
redis:
  host: 
  port: 6379
  password: 
  db: 1
  tls_enable: false
forecast_service:
  base_url: 
  api_key: 
