services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080" 
    environment:
      - CONFIG_FILE=/app/config.yaml 
    depends_on:
      - redis
    volumes:
      - ./config.yaml:/app/config.yaml  
  
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"  
    command: > 
      redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes 
