// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/notification/domain/notification_sender.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

type MockNotificationSender struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSenderMockRecorder
}

type MockNotificationSenderMockRecorder struct {
	mock *MockNotificationSender
}

func NewMockNotificationSender(ctrl *gomock.Controller) *MockNotificationSender {
	mock := &MockNotificationSender{ctrl: ctrl}
	mock.recorder = &MockNotificationSenderMockRecorder{mock}
	return mock
}

func (m *MockNotificationSender) EXPECT() *MockNotificationSenderMockRecorder {
	return m.recorder
}

func (m *MockNotificationSender) Send(email, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", email, text)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockNotificationSenderMockRecorder) Send(email, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationSender)(nil).Send), email, text)
}
