// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/notification/infrastructure/sender/smtp_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

type MockSmtpClient struct {
	ctrl     *gomock.Controller
	recorder *MockSmtpClientMockRecorder
}

type MockSmtpClientMockRecorder struct {
	mock *MockSmtpClient
}

